num = int(input('Digite um número inteiro: '))
print('Tabuada de {}'.format(num))
print('{}X1 = {}'.format(num, num*1))
print('{}X2 = {}'.format(num, num*2))
print('{}X3 = {}'.format(num, num*3))
print('{}X4 = {}'.format(num, num*4))
print('{}X5 = {}'.format(num, num*5))
print('{}X6 = {}'.format(num, num*6))
print('{}X7 = {}'.format(num, num*7))
print('{}X8 = {}'.format(num, num*8))
print('{}X9 = {}'.format(num, num*9))
print('{}X10 = {}'.format(num, num*10))
